# Generated by Django 4.0.1 on 2022-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10)),
                ('birthDate', models.DateField(default='')),
                ('phoneNo', models.CharField(default='', max_length=50)),
                ('aadharNo', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=500)),
                ('zip', models.CharField(default='', max_length=50)),
                ('accountNo', models.IntegerField(default=0)),
                ('currentBalence', models.IntegerField(default=0)),
            ],
        ),
    ]
