# Generated by Django 4.0.1 on 2022-06-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('toTransfer', models.CharField(default='', max_length=50)),
                ('fromTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBank.customerdetail')),
            ],
        ),
    ]
